"""add attendance source_ip and location

Revision ID: 2eb328672b4f
Revises: 0b7f7b0add41
Create Date: 2026-07-08 12:36:46.743234

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2eb328672b4f'
down_revision: Union[str, None] = '0b7f7b0add41'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attendance_days', sa.Column('source_ip', sa.String(length=64), nullable=True))
    op.add_column('attendance_days', sa.Column('location', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('attendance_days', 'location')
    op.drop_column('attendance_days', 'source_ip')
    # ### end Alembic commands ###
